Fix/delivery request more info
poap-xyz/poap-webapp pull request #73
Opened 2021-09-01 20:09 UTC by sebasfavaron

Added extra info requested to be able to review delivery requests correctly
![image](https://user-images.githubusercontent.com/19996944/131737227-30ed85bb-0b15-413a-a4c1-5ce45cf70f0f.png)

2021-09-07 13:06 UTC, rlajous requested changes

2021-09-07 13:06 UTC, rlajous commented on src/backoffice/DeliveriesRequests.tsx
> +        mail: delivery.mail,
You could do desconstructing the object and like this 
```js
const { mail } = delivery;

return {
mail,
}
```

2021-09-07 13:06 UTC, rlajous commented on src/backoffice/DeliveriesRequests.tsx
> +                      <div style={{
Why are you adding in-line styles?

2021-09-07 13:06 UTC, rlajous commented on src/backoffice/DeliveriesRequests.tsx
> +      <div style={{ width: '70%' }}>Id: <a href={`https://poap.gallery/event/${event.id}`} style={{display: 'inline-flex'}} rel="noopener noreferrer" target="_blank">{event.id}</a></div>
Should create a class, repeated code

2021-09-07 13:06 UTC, rlajous commented on src/scss/components/_backoffice.scss
> +          div, a, span {
Instead of targeting the div, a, span maybe for better understanding may have a class so it can be more readable and also instead of `div, a, span` you target `.class`

2021-09-07 13:06 UTC, rlajous commented on src/backoffice/DeliveriesRequests.tsx
> +              const style = j===5 ? {width: '160px'}
What is j? the next person wouldn't know, maybe extract to function and call it with name?

2021-09-07 13:11 UTC, rlajous commented
Why is this not centered?
![image](https://user-images.githubusercontent.com/40175251/132350454-e392a48e-e434-4bbf-bcf9-8bce893b32f8.png)

2021-09-07 13:19 UTC, sebasfavaron commented on src/backoffice/DeliveriesRequests.tsx
> +      let main_event_id = isNaN(ids[0]) ? -1 : ids[0]
yes

2021-09-07 13:20 UTC, sebasfavaron commented on src/backoffice/DeliveriesRequests.tsx
> +        main_event_id: main_event_id,
solving both comments with 'main_event_id: isNaN(ids[0]) ? -1 : ids[0],'

2021-09-07 13:27 UTC, sebasfavaron commented on src/backoffice/DeliveriesRequests.tsx
> +                      <div style={{
wanted to do a styled.div but styled-components was not installed

2021-09-07 14:03 UTC, sebasfavaron commented on src/backoffice/DeliveriesRequests.tsx
> +      <div style={{ width: '70%' }}>Id: <a href={`https://poap.gallery/event/${event.id}`} style={{display: 'inline-flex'}} rel="noopener noreferrer" target="_blank">{event.id}</a></div>
done

2021-09-07 14:31 UTC, sebasfavaron commented on src/backoffice/DeliveriesRequests.tsx
> +              const style = j===5 ? {width: '160px'}
refactored

2021-09-07 14:31 UTC, sebasfavaron commented on src/scss/components/_backoffice.scss
> +          div, a, span {
refactored

2021-09-07 15:16 UTC, rlajous approved these changes

2021-09-13 23:51 UTC, alavarello commented
First we need to merge this [PR](https://github.com/poap-xyz/poap-server/pull/156)

### Fixes:
- Show email in the events info. 
- Center info
![Screenshot from 2021-09-13 17-33-31](https://user-images.githubusercontent.com/19600590/133171601-4d655044-6920-4784-9a4e-557a5ab27689.png)
![Screenshot from 2021-09-13 17-33-13](https://user-images.githubusercontent.com/19600590/133171607-d3257cfa-0dea-4d29-b978-14b658e6b519.png)

2021-09-14 00:12 UTC, alavarello commented
- Fix show email in table

![Screenshot from 2021-09-13 21-12-03](https://user-images.githubusercontent.com/19600590/133173068-1ebfc2e9-a0df-4b02-b1c9-a72627c52dd4.png)

2021-09-14 14:07 UTC, nacho9900 commented
Is an expected behavior ask for each delivery address after fetching a deliveries page?

Maybe we can add this count to be returned by the backend.

![image](https://user-images.githubusercontent.com/20389479/133272327-981abc8b-b2a4-46eb-9376-8130efd47c19.png)

2021-09-14 18:32 UTC, alavarello commented
> Is an expected behavior ask for each delivery address after fetching a deliveries page?
> 
> Maybe we can add this count to be returned by the backend.
> 
> ![image](https://user-images.githubusercontent.com/20389479/133272327-981abc8b-b2a4-46eb-9376-8130efd47c19.png)

For now we are going to leave this. 

But you made me realize that there were various `useEffects` that do the same thing

2021-09-14 19:23 UTC, nacho9900 requested changes

2021-09-14 19:23 UTC, nacho9900 commented on src/scss/components/_backoffice.scss
> -            display: inline-block;
This line breaks `/admin/requests` event column because is an anchord element and it's must be explicitly inline-block in order to gain the ellipsis behavior.

![image](https://user-images.githubusercontent.com/20389479/133320075-8ed23360-600f-4d26-8540-e2a3303e8b37.png)

2021-09-14 19:23 UTC, nacho9900 commented on src/scss/components/_backoffice.scss
> +          .delivery-request-row-div {
This kind of classes affects the maintainability of the style sheets because it's start to grow uncontrollable with classes like `delivery-request-something`, `qr-code-some-other-specific-stuff`, etc. Please use reusable classes.

2021-09-14 22:10 UTC, nacho9900 commented on src/backoffice/DeliveriesRequests.tsx
> +          <div className={'center ellipsis'} style={{ maxWidth: 'none' }}>
`max-width: none` is breaking title ellipsis, ellipsis must contains an explicit width to behave as expected. 

![image](https://user-images.githubusercontent.com/20389479/133340138-fa689681-05b3-4645-b6d1-180150c9b4cc.png)

2021-09-15 13:54 UTC, nacho9900 approved these changes
Tested on dev and workings as expected!

2021-09-15 20:23 UTC, alavarello commented
- Fix center columns
![image](https://user-images.githubusercontent.com/19600590/133504110-8b5a08aa-77b0-426c-b465-27927a333acb.png)

2021-09-17 15:48 UTC, nacho9900 requested changes
Race condition on "Filter by Approval", steps to reproduce:

- Go to last page: 
![image](https://user-images.githubusercontent.com/20389479/133816299-cdef3ccd-a8a8-4bc0-bcc5-9a0fb83ec89c.png)
- Filter by pending:
![image](https://user-images.githubusercontent.com/20389479/133816686-53690c7a-5a76-4ccd-8e43-46b857c5324a.png)
![image](https://user-images.githubusercontent.com/20389479/133816733-d656c891-dc23-4edc-be7c-80aaf6c97b57.png)

The filter is requesting two simultaneous deliveries fetchs, one with incorrect paramentes, and sometimes the incorrect one comes first.

2021-09-24 17:52 UTC, alavarello approved these changes

2021-09-24 17:55 UTC, merged